### ISSUE TITLE
要加个隧道功能吗，就可以在本地添加隧道了

### ISSUE THREAD

**Issue by docker-master** [lmq8267/luci-app-cloudflared#2]
![image](https://github.com/user-attachments/assets/02915f25-c499-4d0d-8f7d-34352442ab96)

**Comment by lmq8267** [comment]
怎么加呢？

**Comment by docker-alex-ai** [comment]
https://github.com/cloudflare/cloudflared/issues/877 这个是官方的，里面有个一年前添加openwrt版本的 issue，没人搭理他，他的应该只是内核，我没用过
我用的应该是 https://github.com/openwrt/packages/tree/master/net/cloudflared 这个 openwrt官方构建的ipk软件包，他这个没你的自定义 环境变量功能，你参考一下 ![image](https://github.com/user-attachments/assets/c378f7a8-9ee4-440c-8049-94dc805f1c45)

**Comment by lmq8267** [comment]
我看了下 ，官方的`luci-app-cloudflared`是基于js写的， 我的openwrt无法使用js的luci，所以我写了这个lua的自用，添加隧道还是去官网吧，我不会用lua写加隧道

**Comment by docker-alex-ai** [comment]
千万别做这个，我用了一下cloudflare中文手册，照着在本地部署了一下，本来以为他是填个认证的东西就能用，没想到，
1 用命令登录 2 创建config.yml 3 好像是开始验证，死活弄不了，不如直接用官方面板用的舒心
